plugins {
    id "base"
}

def registerTargetBuild = { String taskName, String target ->
    tasks.register(taskName, Exec) {
        group = "vital relics"
        description = "Builds ${target}"

        workingDir = rootDir
        executable = "${rootDir}/gradlew"
        args ":${target}:build"
    }
}

registerTargetBuild("buildForge1201", "forge-1.20.1")
registerTargetBuild("buildNeoForge1211", "neoforge-1.21.1")
registerTargetBuild("buildNeoForge1218", "neoforge-1.21.8")
registerTargetBuild("buildNeoForge262", "neoforge-26.2")