pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = "https://maven.neoforged.net/releases" }
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

plugins {
    id "org.gradle.toolchains.foojay-resolver-convention" version "0.8.0"
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}


rootProject.name = "VitalRelics"

include("common")
include("forge-1.20.1")
include("neoforge-1.21.1")
include("neoforge-1.21.8")