modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://raw.githubusercontent.com/leaked32/Vital-Relics/main/update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/vital-relics"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "curios"
type = "required"
versionRange = "[16.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "jei"
type = "optional"
versionRange = "[30,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "touhou_little_maid"
type = "optional"
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"